[tools]
"npm:@scalar/cli" = { version = "2.5.2", trust_policy_excludes = [
  "rollup@2.8.0",
] }

[tasks.watch-openapi]
run = "scalar document serve openapi.yaml --watch"

[tasks.validate-openapi]
run = "scalar document validate openapi.yaml"
