openapi: 3.0.0

servers:
  - url: https://example.com
    description: Local server

info:
  title: Book Metadata Provider
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

security:
  - api_key: []

paths:
  /search:
    get:
      description: Search for books
      operationId: search
      summary: Search for books
      security:
        - api_key: []

      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
        - name: author
          in: query
          required: false
          schema:
            type: string
        - name: mediaType
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/MediaType"

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  matches:
                    type: array
                    items:
                      $ref: "#/components/schemas/BookMetadata"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
                    example: "Invalid query parameter"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
                    example: "Unauthorized"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
                    example: "Internal Server Error"
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: AUTHORIZATION
      in: header

  schemas:
    BookMetadata:
      type: object
      required:
        - title
      properties:
        mediaType:
          $ref: "#/components/schemas/MediaType"
        title:
          type: string
          description: The title of the book
          example: Babel
        subtitle:
          type: string
          description: The subtitle of the book
          example: "Or the Necessity of Violence: An Arcane History of The Oxford Translators' Revolution"
        author:
          deprecated: true
          type: string
          description: The author of the book
          example: R. F. Kuang
        authors:
          type: array
          items:
            type: string
          description: The authors of the book
          example:
            - Susanne Valenti
            - Caroline Peckham
        narrator:
          deprecated: true
          type: string
          description: The narrator of the book
          example: Chris Lew Kum Hoi,Billie Fulford-Brown

        narrators:
          type: array
          items:
            type: string
          description: The narrators of the book
          example:
            - Chris Lew Kum Hoi
            - Billie Fulford-Brown
        publisher:
          type: string
          description: The publisher of the book
          example: HarperCollins
        publishedYear:
          type: string
          description: The year the book was published
          example: "2022"
        description:
          type: string
          description: The description of the book
          example: "A new dark academic fantasy by the New York Times bestselling author of The Poppy War..."
        cover:
          type: string
          description: URL to the cover image
          example: "https://example.com/books/kuang/babel/cover.jpg"
        isbn:
          type: string
          format: isbn
          description: The ISBN of the book
          example: "9780063021457"
        asin:
          type: string
          format: asin
          description: The ASIN of the book
          example: "B09MD95S5V"
        genres:
          type: array
          items:
            type: string
          description: The genres of the book
          example: ["Fantasy", "Historical Fiction", "Dark Academia"]
        tags:
          type: array
          items:
            type: string
          description: The tags of the book
          example: ["secret society", "violent", "victorian", "dark academia"]
        series:
          type: array
          items:
            $ref: "#/components/schemas/SeriesMetadata"
        language:
          type: string
          description: The language of the book
          example: "English"
        duration:
          type: integer
          format: int64
          description: Duration in minutes
          example: 1306

    SeriesMetadata:
      type: object
      required:
        - series
      properties:
        series:
          type: string
          description: The series of the book
          example: "Middle Earth"
        sequence:
          type: string
          description: The sequence of the book in the series. Omit if there's no sequence.
          example: "1"

    MediaType:
      type: string
      description: |
        The media type of the book

        Clients should fall back to `unknown` for backwards compatibility
      enum:
        - book
        - audiobook
        - unknown
