// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetProviderInfoData, GetProviderInfoResponses, SearchData, SearchErrors, SearchResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Search for books
 *
 * Search for books
 */
export const search = <ThrowOnError extends boolean = false>(options: Options<SearchData, ThrowOnError>): RequestResult<SearchResponses, SearchErrors, ThrowOnError> => (options.client ?? client).get<SearchResponses, SearchErrors, ThrowOnError>({
    security: [{ name: 'AUTHORIZATION', type: 'apiKey' }],
    url: '/search',
    ...options
});

/**
 * Get provider information
 *
 * Returns information about the provider, including the provider name and version.
 */
export const getProviderInfo = <ThrowOnError extends boolean = false>(options?: Options<GetProviderInfoData, ThrowOnError>): RequestResult<GetProviderInfoResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetProviderInfoResponses, unknown, ThrowOnError>({ url: '/provider/info', ...options });
