// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://example.com' | (string & {});
};

export type BookMetadata = {
    mediaType?: MediaType;
    /**
     * The unique identifier of the book in the provider's system
     */
    providerId?: string;
    /**
     * The title of the book
     */
    title: string;
    /**
     * The subtitle of the book
     */
    subtitle?: string;
    /**
     * The author of the book
     *
     * @deprecated
     */
    author?: string;
    /**
     * The authors of the book
     */
    authors?: Array<string>;
    /**
     * The narrator of the book
     *
     * @deprecated
     */
    narrator?: string;
    /**
     * The narrators of the book
     */
    narrators?: Array<string>;
    /**
     * The publisher of the book
     */
    publisher?: string;
    /**
     * The year the book was published
     */
    publishedYear?: string;
    /**
     * The date the book was published
     *
     * If both `publishedYear` and `publishedDate` are provided, `publishedDate` takes precedence.
     *
     */
    publishedDate?: string;
    /**
     * The description of the book
     */
    description?: string;
    /**
     * URL to the cover image
     */
    cover?: string;
    /**
     * The ISBN of the book
     *
     * @deprecated
     */
    isbn?: string;
    /**
     * The ISBN-13 of the book
     */
    isbn13?: string;
    /**
     * The ISBN-10 of the book
     */
    isbn10?: string;
    /**
     * The ASIN of the book
     */
    asin?: string;
    /**
     * The genres of the book
     */
    genres?: Array<string>;
    /**
     * The tags of the book
     */
    tags?: Array<string>;
    /**
     * The series that the book belongs to. Omitted if the book is not part of a series.
     *
     * If the book is part of multiple series, lists them all in order of importance.
     * If a book is a combination of multiple parts of a series, lists each part as a separate series entry.
     *
     */
    series?: Array<SeriesMetadata>;
    /**
     * The language of the book
     *
     * In 1.0.0 Used primarily for user-facing purposes, and not for metadata.
     *
     */
    language?: string;
    /**
     * The language code of the book in IETF BCP 47 format
     *
     * This should be preferred over `language` for metadata purposes.
     *
     */
    languageCode?: string;
    /**
     * The original language of the book
     *
     * In 1.0.0 Used primarily for user-facing purposes, and not for metadata.
     *
     */
    originalLanguage?: string;
    /**
     * The original language code of the book in IETF BCP 47 format
     *
     * This should be preferred over `originalLanguage` for metadata purposes.
     *
     */
    originalLanguageCode?: string;
    /**
     * Duration in minutes
     */
    duration?: number;
    /**
     * The number of pages in the book
     */
    pages?: number;
    textDirection?: 'leftToRight' | 'rightToLeft';
};

export type SeriesMetadata = {
    /**
     * The series of the book
     */
    series: string;
    /**
     * The sequence of the book in the series. Omitted if there's no sequence.
     *
     * Kept for backwards compatibility. Servers and clients implementing 1.0.0 should prefer `sequenceNumber` instead.
     *
     *
     * @deprecated
     */
    sequence?: string;
    /**
     * The sequence of the book in the series. Omitted if there's no sequence. May be fractional or even negative.
     *
     */
    sequenceNumber?: number;
    /**
     * The total number of books in the series. Omitted if unknown.
     */
    totalInSeries?: number;
};

/**
 * The media type of the book
 *
 * Clients should fall back to `unknown` for backwards compatibility
 *
 */
export type MediaType = 'book' | 'audiobook' | 'unknown';

export type ProviderInfo = {
    /**
     * The name of the provider
     */
    name?: string;
    /**
     * The version of the provider
     */
    version?: string;
    /**
     * The URL of the provider's avatar
     */
    avatarUrl?: string;
    /**
     * Whether authentication is required to use the provider
     */
    authenticationRequired?: boolean;
};

export type SearchData = {
    body?: never;
    path?: never;
    query: {
        query: string;
        author?: string;
        mediaType?: MediaType;
    };
    url: '/search';
};

export type SearchErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * The error message
         */
        error?: string;
    };
    /**
     * Unauthorized
     */
    401: {
        /**
         * The error message
         */
        error?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * The error message
         */
        error?: string;
    };
};

export type SearchError = SearchErrors[keyof SearchErrors];

export type SearchResponses = {
    /**
     * OK
     */
    200: {
        matches?: Array<BookMetadata>;
    };
};

export type SearchResponse = SearchResponses[keyof SearchResponses];

export type GetProviderInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/provider/info';
};

export type GetProviderInfoResponses = {
    /**
     * OK
     */
    200: ProviderInfo;
};

export type GetProviderInfoResponse = GetProviderInfoResponses[keyof GetProviderInfoResponses];
